"""
GPU Job Generator Module

Generates job scripts for GPU-accelerated HPC jobs.
This module handles MPI+GPU jobs with proper GPU binding.

Design Principles:
==================
- NO HARDCODED VALUES: All values from configuration
- SYSTEM AGNOSTIC: Works on any HPC system with GPUs
- PROPER GPU BINDING: Uses bind.sh for GPU-MPI rank mapping
- CORRECT MPI MAPPING: ppr:X:node:PE=Y format

MPI Command Format (GPU Jobs):
==============================
mpirun -np <total_ranks> --map-by ppr:<ranks_per_node>:node:PE=<cores_per_rank> ./bind.sh $BINARY/<executable> <input>

GPU Binding:
============
- bind.sh script sets CUDA_VISIBLE_DEVICES based on local MPI rank
- Each MPI rank gets one GPU
- CRITICAL: bind.sh wraps the executable, NOT the other way around

Example (4 GPUs/node, 32 cores/node, 4 nodes):
    mpirun -np 16 --map-by ppr:4:node:PE=8 ./bind.sh $BINARY/iPIC3D os-stdin

Author: HPC-ScaleTest Contributors
"""

import logging
from typing import Optional

from .base import JobGeneratorBase, JobGeneratorConfig

logger = logging.getLogger(__name__)


# GPU binding script content - NVIDIA compatible
BIND_SCRIPT_CONTENT = '''#!/bin/bash
# =============================================================================
# GPU Binding Script - Generated by HPC-ScaleTest
# =============================================================================
# This script binds each MPI rank to a unique GPU using CUDA_VISIBLE_DEVICES.
# It reads the local rank from MPI environment variables.
#
# Supported MPI implementations:
#   - OpenMPI (OMPI_COMM_WORLD_LOCAL_RANK)
#   - Intel MPI (MPI_LOCALRANKID)
#   - MPICH/Cray MPICH (PMI_LOCAL_RANK)
#   - SLURM (SLURM_LOCALID)
#   - MVAPICH2 (MV2_COMM_WORLD_LOCAL_RANK)
#
# Usage: ./bind.sh <executable> [args...]
# =============================================================================

# Determine local rank from available environment variables
if [ -n "$OMPI_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
elif [ -n "$MPI_LOCALRANKID" ]; then
    LOCAL_RANK=$MPI_LOCALRANKID
elif [ -n "$PMI_LOCAL_RANK" ]; then
    LOCAL_RANK=$PMI_LOCAL_RANK
elif [ -n "$SLURM_LOCALID" ]; then
    LOCAL_RANK=$SLURM_LOCALID
elif [ -n "$MV2_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$MV2_COMM_WORLD_LOCAL_RANK
else
    LOCAL_RANK=0
fi

# Set GPU visibility - bind this rank to specific GPU
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK

# Also set for AMD GPUs (ROCm)
export ROCR_VISIBLE_DEVICES=$LOCAL_RANK
export HIP_VISIBLE_DEVICES=$LOCAL_RANK

# Debug output (can be disabled in production)
# echo "Rank $OMPI_COMM_WORLD_RANK -> Local $LOCAL_RANK -> GPU $LOCAL_RANK"

# Execute the actual application
exec "$@"
'''


class GPUJobGenerator(JobGeneratorBase):
    """
    Job script generator for GPU-accelerated jobs.
    
    For GPU jobs:
    - 1 MPI rank per GPU
    - CPU cores per rank = total_cores / gpus_per_node
    - GPU binding via bind.sh script
    - mpirun uses --map-by ppr:X:node:PE=Y format
    
    Example (32 cores/node, 4 GPUs/node, 4 nodes):
        - ranks_per_node = 4 (one per GPU)
        - cores_per_rank = 8 (32/4)
        - total_ranks = 16 (4 nodes × 4 GPUs)
        - Command: mpirun -np 16 --map-by ppr:4:node:PE=8 ./bind.sh $BINARY/iPIC3D os-stdin
    """
    
    def __init__(self, config: JobGeneratorConfig):
        """
        Initialize GPU job generator.
        
        Args:
            config: Job generator configuration
        """
        super().__init__(config)
        
        # Validate: gpus_per_node should be > 0 for GPU jobs
        if config.gpus_per_node <= 0:
            raise ValueError(
                f"GPUJobGenerator requires gpus_per_node > 0, got {config.gpus_per_node}. "
                f"For CPU jobs, use CPUJobGenerator instead."
            )
        
        # Calculate derived values
        self.ranks_per_node = config.gpus_per_node
        self.cores_per_rank = config.cpus_per_node // config.gpus_per_node
        
        logger.info(f"GPUJobGenerator initialized:")
        logger.info(f"  GPUs per node: {config.gpus_per_node}")
        logger.info(f"  CPUs per node: {config.cpus_per_node}")
        logger.info(f"  MPI ranks per node: {self.ranks_per_node}")
        logger.info(f"  CPU cores per rank: {self.cores_per_rank}")
    
    def generate_mpi_command(
        self,
        num_nodes: int,
        total_ranks: int,
        ranks_per_node: int,
        cores_per_rank: int
    ) -> str:
        """
        Generate MPI launch command for GPU job.
        
        CRITICAL: The command format must be:
        mpirun -np <total> --map-by ppr:<ranks>:node:PE=<cores> ./bind.sh $BINARY/<exe> <input>
        
        Args:
            num_nodes: Number of nodes
            total_ranks: Total MPI ranks (= num_nodes × GPUs per node)
            ranks_per_node: MPI ranks per node (= GPUs per node)
            cores_per_rank: CPU cores per rank (= CPUs / GPUs)
        
        Returns:
            MPI launch command
        """
        exe_path = f"$BINARY/{self.config.executable}" if self.config.binary_dir else self.config.executable
        input_arg = self.config.input_file if self.config.input_file else ""
        
        if self.config.launcher == "srun":
            # SLURM native launcher with GPU binding
            cmd = (
                f"srun --ntasks={total_ranks} "
                f"--ntasks-per-node={ranks_per_node} "
                f"--cpus-per-task={cores_per_rank} "
                f"--gpu-bind=closest "
                f"{exe_path} {input_arg}"
            )
        else:
            # mpirun with ppr mapping and bind.sh
            # THIS IS THE CORRECT FORMAT: ./bind.sh wraps the executable
            cmd = (
                f"mpirun -np {total_ranks} "
                f"--map-by ppr:{ranks_per_node}:node:PE={cores_per_rank} "
                f"--report-bindings "
                f"./bind.sh {exe_path} {input_arg}"
            )
        
        return cmd.strip()
    
    def generate_bind_script(self) -> str:
        """
        Generate GPU binding script content.
        
        Returns:
            bind.sh script content as string
        """
        return BIND_SCRIPT_CONTENT
    
    def generate_script(
        self,
        num_nodes: int,
        job_name: str,
        working_dir: str,
        procs_decomposition: Optional[tuple] = None,
        **kwargs
    ) -> str:
        """
        Generate complete GPU job script.
        
        Args:
            num_nodes: Number of nodes
            job_name: SLURM job name
            working_dir: Working directory
            procs_decomposition: MPI decomposition (px, py, pz) if needed
            **kwargs: Additional parameters
        
        Returns:
            Complete job script as string
        """
        # Calculate MPI configuration
        ranks_per_node = self.ranks_per_node
        cores_per_rank = self.cores_per_rank
        total_ranks = num_nodes * ranks_per_node
        
        # Override total_ranks if procs_decomposition provided
        if procs_decomposition:
            expected_ranks = procs_decomposition[0] * procs_decomposition[1] * procs_decomposition[2]
            if expected_ranks != total_ranks:
                logger.warning(
                    f"procs_decomposition {procs_decomposition} gives {expected_ranks} ranks, "
                    f"but GPU configuration expects {total_ranks} ranks ({num_nodes} nodes × {ranks_per_node} GPUs/node)"
                )
        
        # Generate script components
        header = self.generate_header_comment(
            num_nodes=num_nodes,
            ranks_per_node=ranks_per_node,
            cores_per_rank=cores_per_rank,
            job_type="GPU"
        )
        
        directives = self.generate_slurm_directives(
            num_nodes=num_nodes,
            job_name=job_name,
            working_dir=working_dir,
            ntasks_per_node=self.config.cpus_per_node,  # Full allocation for QoS
            gpus_per_node=self.config.gpus_per_node
        )
        
        module_loads = self.generate_module_loads()
        env_exports = self.generate_env_exports()
        
        mpi_cmd = self.generate_mpi_command(
            num_nodes=num_nodes,
            total_ranks=total_ranks,
            ranks_per_node=ranks_per_node,
            cores_per_rank=cores_per_rank
        )
        
        # Build complete script
        script = header
        script += "\n".join(directives) + "\n\n"
        script += module_loads + "\n"
        script += env_exports
        
        script += f'''
# Change to working directory
cd {working_dir}

# Set binary location
export BINARY={self.config.binary_dir if self.config.binary_dir else working_dir}

# Set OpenMP threads to cores per MPI rank
export OMP_NUM_THREADS={cores_per_rank}

echo "=========================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Nodes: $SLURM_NNODES"
echo "GPUs per node: {self.config.gpus_per_node}"
echo "MPI ranks per node: {ranks_per_node}"
echo "CPU cores per rank: {cores_per_rank}"
echo "Total MPI ranks: {total_ranks}"
echo "Total GPUs: {num_nodes * self.config.gpus_per_node}"
echo "Working directory: $PWD"
echo "BINARY: $BINARY"
echo "OMP_NUM_THREADS: $OMP_NUM_THREADS"
echo "=========================================="

# =============================================================================
# =============================================================================
# GPU Binding
# =============================================================================
# bind.sh should already exist in the job directory (created by HPC-ScaleTest)
# If not found, create it at runtime as a fallback

if [ ! -f ./bind.sh ]; then
    echo "WARNING: bind.sh not found, creating at runtime..."
    cat > bind.sh << 'BIND_EOF'
{BIND_SCRIPT_CONTENT}
BIND_EOF
    chmod +x bind.sh
fi

echo ""
echo "Starting: $(date)"
echo "Command: {mpi_cmd}"
echo ""

# Execute with timing
start_time="$(date -u +%s.%N)"

{mpi_cmd}

exit_code=$?
end_time="$(date -u +%s.%N)"
elapsed="$(echo "$end_time - $start_time" | bc)"

echo ""
echo "=========================================="
echo "Completed: $(date)"
echo "Exit code: $exit_code"
echo "Elapsed: $elapsed seconds"
echo "=========================================="

exit $exit_code
'''
        
        return script
    
    def get_bind_script_path(self, working_dir: str) -> str:
        """
        Get the path to the bind.sh script.
        
        Args:
            working_dir: Working directory
        
        Returns:
            Full path to bind.sh
        """
        return f"{working_dir}/bind.sh"
