#!/usr/bin/env python3
"""
engine/gpu_execution.py - GPU Execution Module

Handles execution logic for GPU-accelerated HPC jobs.

CRITICAL REQUIREMENTS:
1. BINARY must point to the directory containing the compiled application binary
2. The executable must be the actual application binary, NOT the bind script
3. mpirun must include correct rank, core, and GPU mapping

For GPU jobs:
- One MPI rank per GPU
- CPU cores per rank = CPUs per node / GPUs per node
- GPU binding via CUDA_VISIBLE_DEVICES

Correct Output Pattern:
    export BINARY=<absolute path to build directory>
    
    mpirun -np <total_ranks> \\
           --map-by ppr:<ranks_per_node>:node:PE=<cores_per_rank> \\
           --report-bindings \\
           ./bind.sh $BINARY/<executable> <input>

Author: HPC-ScaleTest Contributors
"""

import os
import logging
from dataclasses import dataclass, field
from typing import List, Optional, Tuple
from pathlib import Path

logger = logging.getLogger(__name__)


# =============================================================================
# GPU Binding Script
# =============================================================================

BIND_SCRIPT_CONTENT = '''#!/bin/bash
# GPU Binding Script - Generated by HPC-ScaleTest
# 
# This script binds each MPI rank to a unique GPU using CUDA_VISIBLE_DEVICES.
# It reads the local rank from OpenMPI environment variables.
#
# Usage: ./bind.sh <executable> [args...]

# Determine local rank from available environment variables
if [ -n "$OMPI_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
elif [ -n "$MPI_LOCALRANKID" ]; then
    LOCAL_RANK=$MPI_LOCALRANKID
elif [ -n "$PMI_LOCAL_RANK" ]; then
    LOCAL_RANK=$PMI_LOCAL_RANK
elif [ -n "$SLURM_LOCALID" ]; then
    LOCAL_RANK=$SLURM_LOCALID
elif [ -n "$MV2_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$MV2_COMM_WORLD_LOCAL_RANK
else
    LOCAL_RANK=0
fi

# Set CUDA_VISIBLE_DEVICES to bind this rank to a specific GPU
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK

# Execute the actual application
exec "$@"
'''


@dataclass
class GPUJobConfig:
    """Configuration for a GPU-accelerated job."""
    
    # Node configuration
    num_nodes: int
    cpus_per_node: int
    gpus_per_node: int
    
    # MPI configuration (derived from GPUs)
    mpi_ranks_per_node: int = field(init=False)
    cores_per_rank: int = field(init=False)
    total_mpi_ranks: int = field(init=False)
    total_gpus: int = field(init=False)
    
    # Problem decomposition
    procs_x: int = 1
    procs_y: int = 1
    procs_z: int = 1
    
    # Binary configuration
    binary_dir: str = ""      # Absolute path to build directory
    executable_name: str = "" # Name of the executable (e.g., "iPIC3D")
    
    def __post_init__(self):
        """Compute derived values."""
        # For GPU jobs: 1 MPI rank per GPU
        self.mpi_ranks_per_node = self.gpus_per_node
        
        # CPU cores per rank
        self.cores_per_rank = self.cpus_per_node // self.gpus_per_node
        
        # Total ranks and GPUs
        self.total_mpi_ranks = self.num_nodes * self.mpi_ranks_per_node
        self.total_gpus = self.num_nodes * self.gpus_per_node
        
        # Verify decomposition
        expected_total = self.procs_x * self.procs_y * self.procs_z
        if expected_total != self.total_mpi_ranks:
            logger.warning(
                f"MPI decomposition {self.procs_x}×{self.procs_y}×{self.procs_z}={expected_total} "
                f"doesn't match total_mpi_ranks={self.total_mpi_ranks}"
            )
    
    @property
    def executable_path(self) -> str:
        """Get full path to executable."""
        if self.binary_dir and self.executable_name:
            return f"$BINARY/{self.executable_name}"
        return self.executable_name


class GPUExecutionEngine:
    """
    Execution engine for GPU-accelerated jobs.
    
    This handles:
    - GPU topology detection
    - Correct bind.sh script generation
    - MPI command generation with proper mapping
    - SLURM resource allocation
    
    CRITICAL: This engine ensures:
    1. BINARY points to build directory (not PWD)
    2. Executable is the actual binary (not bind.sh)
    3. mpirun uses ppr:X:node:PE=Y mapping
    """
    
    def __init__(self, partition: str = ""):
        """
        Initialize GPU execution engine.
        
        Args:
            partition: SLURM partition name
        """
        self.partition = partition
        self._cpus_per_node: Optional[int] = None
        self._gpus_per_node: Optional[int] = None
    
    def detect_topology(self) -> Tuple[int, int]:
        """
        Detect CPUs and GPUs per node.
        
        Returns:
            Tuple (cpus_per_node, gpus_per_node)
        """
        import subprocess
        
        # Detect CPUs
        cpus = self._detect_cpus()
        gpus = self._detect_gpus()
        
        self._cpus_per_node = cpus
        self._gpus_per_node = gpus
        
        logger.info(f"Detected topology: {cpus} CPUs, {gpus} GPUs per node")
        
        return (cpus, gpus)
    
    def _detect_cpus(self) -> int:
        """Detect CPUs per node."""
        import subprocess
        
        # Method 1: SLURM environment
        if 'SLURM_CPUS_ON_NODE' in os.environ:
            return int(os.environ['SLURM_CPUS_ON_NODE'])
        
        if 'SLURM_JOB_CPUS_PER_NODE' in os.environ:
            val = os.environ['SLURM_JOB_CPUS_PER_NODE']
            return int(val.split('(')[0])
        
        # Method 2: sinfo query
        if self.partition:
            try:
                result = subprocess.run(
                    ['sinfo', '-p', self.partition, '-N', '-h', '-o', '%c'],
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                if result.returncode == 0 and result.stdout.strip():
                    return int(result.stdout.strip().split()[0])
            except Exception:
                pass
        
        # Method 3: System
        return os.cpu_count() or 1
    
    def _detect_gpus(self) -> int:
        """Detect GPUs per node."""
        import subprocess
        import re
        
        # Method 1: SLURM environment
        if 'SLURM_GPUS_ON_NODE' in os.environ:
            return int(os.environ['SLURM_GPUS_ON_NODE'])
        
        if 'SLURM_GPUS_PER_NODE' in os.environ:
            return int(os.environ['SLURM_GPUS_PER_NODE'])
        
        if 'CUDA_VISIBLE_DEVICES' in os.environ:
            devs = os.environ['CUDA_VISIBLE_DEVICES']
            if devs and devs.lower() not in ('', 'nodevfiles'):
                return len([d for d in devs.split(',') if d.strip()])
        
        # Method 2: sinfo query
        if self.partition:
            try:
                result = subprocess.run(
                    ['sinfo', '-p', self.partition, '-N', '-h', '-o', '%G'],
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                if result.returncode == 0 and result.stdout.strip():
                    gres = result.stdout.strip().split()[0]
                    match = re.search(r'gpu:(?:\w+:)?(\d+)', gres)
                    if match:
                        return int(match.group(1))
            except Exception:
                pass
        
        # Method 3: nvidia-smi
        try:
            result = subprocess.run(
                ['nvidia-smi', '--query-gpu=count', '--format=csv,noheader'],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0:
                return int(result.stdout.strip().split('\n')[0])
        except Exception:
            pass
        
        return 0
    
    @property
    def cpus_per_node(self) -> int:
        """Get cached or detect CPUs per node."""
        if self._cpus_per_node is None:
            self.detect_topology()
        return self._cpus_per_node
    
    @property
    def gpus_per_node(self) -> int:
        """Get cached or detect GPUs per node."""
        if self._gpus_per_node is None:
            self.detect_topology()
        return self._gpus_per_node
    
    def create_job_config(
        self,
        num_nodes: int,
        binary_dir: str = "",
        executable_name: str = "",
        procs_decomp: Tuple[int, int, int] = None
    ) -> GPUJobConfig:
        """
        Create job configuration for GPU execution.
        
        Args:
            num_nodes: Number of nodes
            binary_dir: Absolute path to build directory (REQUIRED)
            executable_name: Name of executable (REQUIRED)
            procs_decomp: MPI decomposition (px, py, pz)
            
        Returns:
            GPUJobConfig with all values computed
        """
        cpus = self.cpus_per_node
        gpus = self.gpus_per_node
        
        if gpus == 0:
            raise ValueError("No GPUs detected. Use CPUExecutionEngine for CPU-only jobs.")
        
        total_ranks = num_nodes * gpus  # 1 rank per GPU
        
        # Compute or validate decomposition
        if procs_decomp is None:
            procs_decomp = self._compute_decomposition(total_ranks)
        
        return GPUJobConfig(
            num_nodes=num_nodes,
            cpus_per_node=cpus,
            gpus_per_node=gpus,
            procs_x=procs_decomp[0],
            procs_y=procs_decomp[1],
            procs_z=procs_decomp[2],
            binary_dir=binary_dir,
            executable_name=executable_name
        )
    
    def _compute_decomposition(self, total_ranks: int) -> Tuple[int, int, int]:
        """Compute a balanced MPI decomposition."""
        factors = []
        n = total_ranks
        for p in [2, 3, 5, 7]:
            while n % p == 0:
                factors.append(p)
                n //= p
        if n > 1:
            factors.append(n)
        
        px, py, pz = 1, 1, 1
        for i, f in enumerate(sorted(factors, reverse=True)):
            if i % 3 == 0:
                px *= f
            elif i % 3 == 1:
                py *= f
            else:
                pz *= f
        
        return (px, py, pz)
    
    def generate_bind_script(self, output_dir: Path) -> Path:
        """
        Generate the GPU binding script.
        
        Args:
            output_dir: Directory to write bind.sh
            
        Returns:
            Path to generated bind.sh
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        bind_path = output_dir / "bind.sh"
        with open(bind_path, 'w') as f:
            f.write(BIND_SCRIPT_CONTENT)
        
        # Make executable
        os.chmod(bind_path, 0o755)
        
        logger.info(f"Generated GPU binding script: {bind_path}")
        return bind_path
    
    def generate_mpirun_command(
        self,
        config: GPUJobConfig,
        executable: str,
        args: List[str] = None,
        bind_script: str = "./bind.sh",
        report_bindings: bool = True
    ) -> List[str]:
        """
        Generate mpirun command for GPU job.
        
        CRITICAL: The command follows this pattern:
            mpirun -np <total_ranks> \\
                   --map-by ppr:<ranks_per_node>:node:PE=<cores_per_rank> \\
                   --report-bindings \\
                   ./bind.sh $BINARY/<executable> <args>
        
        Args:
            config: GPU job configuration
            executable: Path to executable (or $BINARY/<name>)
            args: Arguments for executable
            bind_script: Path to GPU binding script
            report_bindings: Include --report-bindings
            
        Returns:
            List of command components
        """
        args = args or []
        
        cmd = [
            'mpirun',
            '-np', str(config.total_mpi_ranks),
            '--map-by', f'ppr:{config.mpi_ranks_per_node}:node:PE={config.cores_per_rank}',
        ]
        
        if report_bindings:
            cmd.append('--report-bindings')
        
        # GPU binding wrapper
        cmd.append(bind_script)
        
        # Executable (NOT the bind script!)
        cmd.append(executable)
        
        # Arguments
        cmd.extend(args)
        
        return cmd
    
    def generate_mpirun_string(
        self,
        config: GPUJobConfig,
        executable: str,
        args: List[str] = None,
        bind_script: str = "./bind.sh",
        report_bindings: bool = True
    ) -> str:
        """Generate mpirun command as string."""
        cmd = self.generate_mpirun_command(
            config, executable, args, bind_script, report_bindings
        )
        return ' '.join(cmd)
    
    def generate_slurm_directives(
        self,
        config: GPUJobConfig,
        job_name: str,
        time_limit: str = "02:00:00",
        account: str = None,
        qos: str = None,
        exclusive: bool = True
    ) -> List[str]:
        """
        Generate SLURM directives for GPU job.
        
        CRITICAL: Uses FULL CPU count for --ntasks-per-node (not MPI ranks).
        
        Args:
            config: GPU job configuration
            job_name: SLURM job name
            time_limit: Time limit (HH:MM:SS)
            account: SLURM account
            qos: Quality of service
            exclusive: Exclusive node access
            
        Returns:
            List of SLURM directive lines
        """
        directives = [
            f"#SBATCH --job-name={job_name}",
            f"#SBATCH --nodes={config.num_nodes}",
            # CRITICAL: Full CPU allocation, NOT MPI ranks
            f"#SBATCH --ntasks-per-node={config.cpus_per_node}",
            f"#SBATCH --gres=gpu:{config.gpus_per_node}",
            f"#SBATCH --time={time_limit}",
        ]
        
        if self.partition:
            directives.append(f"#SBATCH --partition={self.partition}")
        
        if account:
            directives.append(f"#SBATCH --account={account}")
        
        if qos:
            directives.append(f"#SBATCH --qos={qos}")
        
        if exclusive:
            directives.append("#SBATCH --exclusive")
        
        return directives
    
    def generate_job_script(
        self,
        config: GPUJobConfig,
        job_name: str,
        args: List[str] = None,
        modules: List[str] = None,
        time_limit: str = "02:00:00",
        account: str = None,
        qos: str = None,
        working_dir: str = "."
    ) -> str:
        """
        Generate complete job script for GPU execution.
        
        Args:
            config: GPU job configuration
            job_name: SLURM job name
            args: Arguments for executable
            modules: Module load commands
            time_limit: Time limit
            account: SLURM account
            qos: Quality of service
            working_dir: Working directory
            
        Returns:
            Complete job script as string
        """
        args = args or []
        modules = modules or []
        
        # SLURM directives
        directives = self.generate_slurm_directives(
            config, job_name, time_limit, account, qos
        )
        
        # MPI command
        mpi_cmd = self.generate_mpirun_string(
            config,
            f"$BINARY/{config.executable_name}",
            args
        )
        
        script = f'''#!/bin/bash
# =============================================================================
# GPU Job Script - Generated by HPC-ScaleTest
# =============================================================================
# Partition: {self.partition}
# Nodes: {config.num_nodes}
# GPUs per node: {config.gpus_per_node}
# CPUs per node: {config.cpus_per_node}
#
# MPI Configuration:
#   Total ranks: {config.total_mpi_ranks} (1 per GPU)
#   Ranks per node: {config.mpi_ranks_per_node}
#   Cores per rank: {config.cores_per_rank}
# =============================================================================

{chr(10).join(directives)}
#SBATCH --output={working_dir}/job_%j.out
#SBATCH --error={working_dir}/job_%j.err

# =============================================================================
# Environment Setup
# =============================================================================
'''
        
        for mod in modules:
            script += f"{mod}\n"
        
        script += f'''
# CRITICAL: BINARY must point to build directory, NOT $PWD
export BINARY={config.binary_dir}

echo "=========================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Nodes: $SLURM_NNODES"
echo "GPUs per node: {config.gpus_per_node}"
echo "CPUs per node: {config.cpus_per_node}"
echo "MPI ranks per node: {config.mpi_ranks_per_node}"
echo "BINARY: $BINARY"
echo "=========================================="

cd {working_dir}

# Set OpenMP threads to cores per rank
export OMP_NUM_THREADS={config.cores_per_rank}

# =============================================================================
# GPU Binding Script
# =============================================================================
cat > bind.sh << 'BIND_EOF'
#!/bin/bash
if [ -n "$OMPI_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
elif [ -n "$SLURM_LOCALID" ]; then
    LOCAL_RANK=$SLURM_LOCALID
else
    LOCAL_RANK=0
fi
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK
exec "$@"
BIND_EOF
chmod +x bind.sh

# =============================================================================
# Execute Application
# =============================================================================
echo ""
echo "Starting: $(date)"
echo "Command: {mpi_cmd}"
echo ""

start_time=$(date +%s.%N)

{mpi_cmd}

exit_code=$?
end_time=$(date +%s.%N)
elapsed=$(echo "$end_time - $start_time" | bc)

echo ""
echo "=========================================="
echo "Completed: $(date)"
echo "Exit code: $exit_code"
echo "Elapsed: $elapsed seconds"
echo "=========================================="

exit $exit_code
'''
        
        return script


# =============================================================================
# Self-test
# =============================================================================

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
    
    print("=" * 70)
    print(" GPU Execution Module - Self Test")
    print("=" * 70)
    
    engine = GPUExecutionEngine(partition="boost_usr_prod")
    engine._cpus_per_node = 32
    engine._gpus_per_node = 4
    
    print(f"\n  Partition: boost_usr_prod")
    print(f"  CPUs per node: {engine.cpus_per_node}")
    print(f"  GPUs per node: {engine.gpus_per_node}")
    
    # Test configurations
    print("\n  Testing job configurations:")
    for nodes in [1, 2, 4]:
        config = engine.create_job_config(
            num_nodes=nodes,
            binary_dir="/path/to/build",
            executable_name="iPIC3D"
        )
        
        print(f"\n    {nodes} node(s):")
        print(f"      Total MPI ranks: {config.total_mpi_ranks}")
        print(f"      Ranks per node: {config.mpi_ranks_per_node}")
        print(f"      Cores per rank: {config.cores_per_rank}")
        print(f"      Total GPUs: {config.total_gpus}")
        
        # Verify derived values
        assert config.mpi_ranks_per_node == 4, f"Expected 4 ranks/node, got {config.mpi_ranks_per_node}"
        assert config.cores_per_rank == 8, f"Expected 8 cores/rank, got {config.cores_per_rank}"
        assert config.total_mpi_ranks == nodes * 4
        assert config.total_gpus == nodes * 4
    
    # Test mpirun command
    print("\n  Testing mpirun command generation:")
    config = engine.create_job_config(
        num_nodes=4,
        binary_dir="/path/to/build",
        executable_name="iPIC3D"
    )
    
    cmd = engine.generate_mpirun_string(config, "$BINARY/iPIC3D", ["os-stdin"])
    print(f"    Command: {cmd}")
    
    # Verify command format
    assert "-np 16" in cmd, "Missing -np 16"
    assert "ppr:4:node:PE=8" in cmd, "Missing ppr:4:node:PE=8"
    assert "./bind.sh" in cmd, "Missing bind.sh"
    assert "$BINARY/iPIC3D" in cmd, "Missing executable"
    assert "os-stdin" in cmd, "Missing argument"
    
    print("\n  ✓ Command format correct:")
    print("    ✓ -np 16 (4 nodes × 4 GPUs)")
    print("    ✓ --map-by ppr:4:node:PE=8")
    print("    ✓ ./bind.sh wrapper")
    print("    ✓ $BINARY/iPIC3D (actual executable)")
    
    # Test SLURM directives
    print("\n  Testing SLURM directives:")
    directives = engine.generate_slurm_directives(config, "test_job")
    directives_str = "\n".join(directives)
    
    assert "--ntasks-per-node=32" in directives_str, "Should use full CPU count"
    assert "--gres=gpu:4" in directives_str, "Should request GPUs"
    
    print("    ✓ --ntasks-per-node=32 (full CPU allocation)")
    print("    ✓ --gres=gpu:4")
    
    # Test job script
    print("\n  Testing job script generation:")
    script = engine.generate_job_script(
        config,
        job_name="test_job",
        args=["os-stdin"],
        modules=["module load cuda/12.0"]
    )
    
    assert "export BINARY=/path/to/build" in script, "Missing BINARY export"
    assert "mpirun -np 16" in script, "Missing mpirun command"
    assert "./bind.sh $BINARY/iPIC3D" in script, "Missing correct command format"
    
    print("    ✓ BINARY set to build directory")
    print("    ✓ mpirun with correct arguments")
    print("    ✓ bind.sh wraps executable")
    
    print("\n" + "=" * 70)
    print(" All tests PASSED")
    print("=" * 70)
