#!/usr/bin/env python3
"""
core/slurm_script.py - SLURM Job Script Generator

This module generates SLURM job scripts with correct resource allocation.

CRITICAL DISTINCTION:
=====================
There are TWO different resource specifications:

1. SLURM Resource Allocation (full node):
   - `#SBATCH --ntasks-per-node=32` - Request all CPUs on node
   - `#SBATCH --gres=gpu:4` - Request all GPUs on node
   - This ensures exclusive node access and proper accounting

2. MPI Execution (actual tasks):
   - `mpirun -np 16 --map-by ppr:4:node:PE=8` - Run 4 MPI ranks per node
   - Each rank gets 8 CPU cores via PE=8
   - This is the actual parallel execution configuration

For Leonardo Booster (32 cores, 4 GPUs per node):
- SLURM allocates: 32 CPUs, 4 GPUs per node (full node)
- MPI runs: 4 ranks per node, 8 cores each (actual execution)

Author: HPC-ScaleTest Contributors
"""

import os
import logging
from dataclasses import dataclass
from typing import List, Optional, Dict

# Import hardware topology
try:
    from core.hardware import (
        HardwareTopology, MPIConfiguration, TopologyDetector,
        detect_topology, get_mpi_config, generate_gpu_bind_script,
        GPU_BIND_SCRIPT
    )
    HAS_HARDWARE_MODULE = True
except ImportError:
    HAS_HARDWARE_MODULE = False

logger = logging.getLogger(__name__)


@dataclass
class SlurmJobConfig:
    """Configuration for a SLURM job."""
    job_name: str
    num_nodes: int
    partition: str
    
    # Resource allocation (full node)
    cpus_per_node: int  # Total CPUs to allocate (full node)
    gpus_per_node: int  # GPUs to allocate (full node)
    
    # MPI execution (actual tasks)
    mpi_ranks_per_node: int  # Actual MPI ranks to run
    cores_per_rank: int      # Cores per MPI rank
    
    # Optional settings
    time_limit: str = "02:00:00"
    account: Optional[str] = None
    qos: Optional[str] = None
    exclusive: bool = True
    constraint: Optional[str] = None
    reservation: Optional[str] = None
    mail_user: Optional[str] = None
    memory_per_node: Optional[str] = None
    working_dir: str = "."
    
    @property
    def total_mpi_ranks(self) -> int:
        """Total MPI ranks across all nodes."""
        return self.num_nodes * self.mpi_ranks_per_node
    
    @property
    def total_gpus(self) -> int:
        """Total GPUs across all nodes."""
        return self.num_nodes * self.gpus_per_node
    
    @property
    def is_gpu_job(self) -> bool:
        """Check if this is a GPU job."""
        return self.gpus_per_node > 0


def generate_slurm_job_script(
    config: SlurmJobConfig,
    executable: str,
    args: List[str] = None,
    env_setup: List[str] = None,
    include_gpu_binding: bool = True,
) -> str:
    """
    Generate a complete SLURM job script.
    
    IMPORTANT: This function correctly separates:
    - SLURM resource allocation (full node)
    - MPI execution parameters (actual tasks)
    
    Args:
        config: SlurmJobConfig with job parameters
        executable: Path to executable
        args: Arguments for executable
        env_setup: Environment setup commands (module loads)
        include_gpu_binding: Include GPU binding script for GPU jobs
    
    Returns:
        Complete SLURM job script as string
    
    Example (Leonardo Booster, 4 nodes):
        SLURM allocates:
            #SBATCH --ntasks-per-node=32  (full node)
            #SBATCH --gres=gpu:4
        
        MPI executes:
            mpirun -np 16 --map-by ppr:4:node:PE=8 ./bind.sh <executable>
    """
    args = args or []
    env_setup = env_setup or []
    
    script = f'''#!/bin/bash
# =============================================================================
# SLURM Job Script - Generated by HPC-ScaleTest
# =============================================================================
# Partition: {config.partition}
# Node count: {config.num_nodes}
# 
# Hardware Topology:
#   CPU cores per node: {config.cpus_per_node}
#   GPUs per node: {config.gpus_per_node}
#
# MPI Execution Configuration:
#   MPI ranks per node: {config.mpi_ranks_per_node}
#   Cores per rank: {config.cores_per_rank}
#   Total MPI ranks: {config.total_mpi_ranks}
#
# IMPORTANT: SLURM allocation uses FULL node resources for accounting,
# while MPI execution uses the derived rank/core mapping.
# =============================================================================

#SBATCH --job-name={config.job_name}
#SBATCH --nodes={config.num_nodes}
#SBATCH --partition={config.partition}
'''
    
    # SLURM Resource Allocation - FULL NODE
    # Use cpus_per_node (full allocation) NOT mpi_ranks_per_node
    script += f"#SBATCH --ntasks-per-node={config.cpus_per_node}\n"
    
    if config.is_gpu_job:
        script += f"#SBATCH --gres=gpu:{config.gpus_per_node}\n"
    
    if config.account:
        script += f"#SBATCH --account={config.account}\n"
    
    if config.qos:
        script += f"#SBATCH --qos={config.qos}\n"
    
    script += f"#SBATCH --time={config.time_limit}\n"
    script += f"#SBATCH --output={config.working_dir}/job_%j.out\n"
    script += f"#SBATCH --error={config.working_dir}/job_%j.err\n"
    
    if config.exclusive:
        script += "#SBATCH --exclusive\n"
    
    if config.constraint:
        script += f"#SBATCH --constraint={config.constraint}\n"
    
    if config.reservation:
        script += f"#SBATCH --reservation={config.reservation}\n"
    
    if config.mail_user:
        script += f"#SBATCH --mail-type=ALL\n"
        script += f"#SBATCH --mail-user={config.mail_user}\n"
    
    if config.memory_per_node:
        script += f"#SBATCH --mem={config.memory_per_node}\n"
    
    # Environment setup
    script += '''
# =============================================================================
# Environment Setup
# =============================================================================
'''
    
    for cmd in env_setup:
        script += f"{cmd}\n"
    
    script += f'''
echo "=========================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Nodes: $SLURM_NNODES"
echo "Partition: $SLURM_JOB_PARTITION"
echo "CPUs per node: $SLURM_CPUS_ON_NODE"
echo "GPUs per node: ${{SLURM_GPUS_ON_NODE:-0}}"
echo "=========================================="

# Set OpenMP threads to cores per MPI rank
export OMP_NUM_THREADS={config.cores_per_rank}

# Change to working directory
cd {config.working_dir}
'''
    
    # GPU binding script (for GPU jobs)
    if config.is_gpu_job and include_gpu_binding:
        script += '''
# =============================================================================
# GPU Binding Script
# =============================================================================
# Uses OMPI_COMM_WORLD_LOCAL_RANK to set CUDA_VISIBLE_DEVICES
# Each MPI rank is bound to a unique GPU
# =============================================================================
cat > bind.sh << 'BIND_EOF'
#!/bin/bash
if [ -n "$OMPI_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
elif [ -n "$MPI_LOCALRANKID" ]; then
    LOCAL_RANK=$MPI_LOCALRANKID
elif [ -n "$PMI_LOCAL_RANK" ]; then
    LOCAL_RANK=$PMI_LOCAL_RANK
elif [ -n "$SLURM_LOCALID" ]; then
    LOCAL_RANK=$SLURM_LOCALID
else
    LOCAL_RANK=0
fi
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK
exec "$@"
BIND_EOF
chmod +x bind.sh
'''
    
    # Build mpirun command
    # Formula: -np = nodes × ranks_per_node
    #          --map-by ppr:ranks:node:PE=cores
    mpi_np = config.total_mpi_ranks
    mpi_ppr = config.mpi_ranks_per_node
    mpi_pe = config.cores_per_rank
    
    mpi_cmd_parts = [
        'mpirun',
        f'-np {mpi_np}',
        f'--map-by ppr:{mpi_ppr}:node:PE={mpi_pe}',
        '--report-bindings',
    ]
    
    if config.is_gpu_job and include_gpu_binding:
        mpi_cmd_parts.append('./bind.sh')
    
    mpi_cmd_parts.append(executable)
    mpi_cmd_parts.extend(args)
    
    mpi_cmd = ' '.join(mpi_cmd_parts)
    
    script += f'''
# =============================================================================
# Execute Application
# =============================================================================
echo "Starting: $(date)"
echo ""
echo "MPI Configuration:"
echo "  Total ranks: {mpi_np}"
echo "  Ranks per node: {mpi_ppr}"
echo "  Cores per rank: {mpi_pe}"
echo ""
echo "Command: {mpi_cmd}"
echo ""

start_time=$(date +%s.%N)

{mpi_cmd}

exit_code=$?
end_time=$(date +%s.%N)
elapsed=$(echo "$end_time - $start_time" | bc)

echo ""
echo "=========================================="
echo "Job completed at: $(date)"
echo "Exit code: $exit_code"
echo "Elapsed time: $elapsed seconds"
echo "=========================================="

exit $exit_code
'''
    
    return script


def create_job_config_from_topology(
    job_name: str,
    num_nodes: int,
    partition: str,
    topology: HardwareTopology = None,
    **kwargs
) -> SlurmJobConfig:
    """
    Create SlurmJobConfig from detected hardware topology.
    
    Args:
        job_name: Name for the job
        num_nodes: Number of nodes
        partition: SLURM partition name
        topology: Pre-detected topology (will detect if None)
        **kwargs: Additional SlurmJobConfig parameters
    
    Returns:
        SlurmJobConfig with correct resource allocation
    
    Example:
        >>> config = create_job_config_from_topology(
        ...     "scaling_test", 4, "boost_usr_prod",
        ...     time_limit="04:00:00"
        ... )
        >>> print(config.cpus_per_node)  # 32 (full allocation)
        >>> print(config.mpi_ranks_per_node)  # 4 (actual ranks)
    """
    if topology is None:
        if not HAS_HARDWARE_MODULE:
            raise RuntimeError("Hardware module not available for topology detection")
        topology = detect_topology(partition)
    
    return SlurmJobConfig(
        job_name=job_name,
        num_nodes=num_nodes,
        partition=partition,
        cpus_per_node=topology.cpu_cores_per_node,
        gpus_per_node=topology.gpus_per_node,
        mpi_ranks_per_node=topology.mpi_ranks_per_node,
        cores_per_rank=topology.cores_per_rank,
        **kwargs
    )


# =============================================================================
# Self-test
# =============================================================================

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
    
    print("=" * 70)
    print(" SLURM Job Script Generator - Self Test")
    print("=" * 70)
    
    # Test with Leonardo Booster configuration
    print("\n[Test] Leonardo Booster: 32 cores, 4 GPUs")
    
    config = SlurmJobConfig(
        job_name="test_job",
        num_nodes=4,
        partition="boost_usr_prod",
        cpus_per_node=32,       # Full node allocation
        gpus_per_node=4,
        mpi_ranks_per_node=4,   # 1 rank per GPU
        cores_per_rank=8,       # 32 / 4 = 8
        account="my_account",
        time_limit="02:00:00",
    )
    
    script = generate_slurm_job_script(
        config,
        "$BINARY/iPIC3D",
        ["os-stdin"],
        ["module load cuda/12.0", "module load openmpi/4.1"]
    )
    
    # Verify key elements
    print("\n  Verifying script contents:")
    
    # Check SLURM directives
    assert "#SBATCH --ntasks-per-node=32" in script, "Missing full CPU allocation"
    print("  ✓ #SBATCH --ntasks-per-node=32 (full node allocation)")
    
    assert "#SBATCH --gres=gpu:4" in script, "Missing GPU allocation"
    print("  ✓ #SBATCH --gres=gpu:4")
    
    # Check MPI command
    assert "mpirun -np 16" in script, "Wrong total MPI ranks"
    print("  ✓ mpirun -np 16 (4 nodes × 4 ranks)")
    
    assert "ppr:4:node:PE=8" in script, "Wrong MPI mapping"
    print("  ✓ --map-by ppr:4:node:PE=8")
    
    assert "./bind.sh" in script, "Missing GPU binding"
    print("  ✓ GPU binding script included")
    
    # Print sample of generated script
    print("\n  Sample script output (first 30 lines):")
    for i, line in enumerate(script.split('\n')[:30]):
        print(f"    {line}")
    print("    ...")
    
    print("\n" + "=" * 70)
    print(" All tests PASSED")
    print("=" * 70)
