#!/usr/bin/env python3
"""
core/unified_execution.py - Unified Execution Module

This module provides a single source of truth for:
1. Hardware topology detection (no hardcoded values)
2. MPI configuration derivation
3. SLURM job script generation
4. GPU binding script generation
5. Incremental result tracking

CRITICAL FIXES:
- Removed hardcoded CPU/GPU counts
- Fixed SLURM --ntasks-per-node (uses full CPU count, not MPI ranks)
- Fixed BINARY path (absolute path, not ${PWD})
- Fixed mpirun mapping (ppr:R:node:PE=C)
- Fixed GPU binding (CUDA_VISIBLE_DEVICES via local rank)
- Separated CPU and GPU execution paths
- Eliminated duplicate logic

Author: HPC-ScaleTest Contributors
"""

import os
import re
import json
import logging
import subprocess
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Tuple, Any
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


# =============================================================================
# CONSTANTS (no site-specific values)
# =============================================================================

# GPU binding script content - uses OMPI_COMM_WORLD_LOCAL_RANK with fallbacks
GPU_BIND_SCRIPT = '''#!/bin/bash
# GPU Binding Script - Generated by HPC-ScaleTest
#
# This script binds each MPI rank to a unique GPU using CUDA_VISIBLE_DEVICES.
# It uses the local rank within a node to determine which GPU to use.
#
# Priority order for local rank detection:
#   1. OMPI_COMM_WORLD_LOCAL_RANK (OpenMPI)
#   2. MV2_COMM_WORLD_LOCAL_RANK (MVAPICH2)
#   3. PMI_LOCAL_RANK (Intel MPI)
#   4. SLURM_LOCALID (SLURM native)
#   5. Default to 0

# Determine local rank
if [ -n "$OMPI_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
elif [ -n "$MV2_COMM_WORLD_LOCAL_RANK" ]; then
    LOCAL_RANK=$MV2_COMM_WORLD_LOCAL_RANK
elif [ -n "$PMI_LOCAL_RANK" ]; then
    LOCAL_RANK=$PMI_LOCAL_RANK
elif [ -n "$SLURM_LOCALID" ]; then
    LOCAL_RANK=$SLURM_LOCALID
else
    LOCAL_RANK=0
fi

# Bind this rank to a specific GPU
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK

# Execute the actual application
exec "$@"
'''


# =============================================================================
# ENUMS
# =============================================================================

class GPUVendor(Enum):
    """GPU vendor types."""
    NVIDIA = "nvidia"
    AMD = "amd"
    INTEL = "intel"
    NONE = "none"


class ScalingType(Enum):
    """Scaling test types."""
    WEAK = "weak"
    STRONG = "strong"


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class HardwareTopology:
    """
    Hardware topology for a compute node.
    
    All values are detected at runtime, not hardcoded.
    This is the SINGLE SOURCE OF TRUTH for hardware info.
    """
    partition: str
    cpu_cores_per_node: int
    gpus_per_node: int = 0
    gpu_vendor: GPUVendor = GPUVendor.NONE
    memory_per_node_gb: int = 0
    detection_method: str = "unknown"
    
    # Derived values (computed in __post_init__)
    mpi_ranks_per_node: int = field(init=False)
    cores_per_rank: int = field(init=False)
    is_gpu_partition: bool = field(init=False)
    
    def __post_init__(self):
        """
        Compute derived values.
        
        CRITICAL FORMULAS:
        - GPU jobs: ranks_per_node = gpus_per_node (1 rank per GPU)
        - GPU jobs: cores_per_rank = cpus / gpus
        - CPU jobs: ranks_per_node = cpus (1 rank per core)
        - CPU jobs: cores_per_rank = 1
        """
        self.is_gpu_partition = self.gpus_per_node > 0
        
        if self.is_gpu_partition:
            # GPU job: 1 MPI rank per GPU
            self.mpi_ranks_per_node = self.gpus_per_node
            self.cores_per_rank = self.cpu_cores_per_node // self.gpus_per_node
        else:
            # CPU-only job: 1 MPI rank per core
            self.mpi_ranks_per_node = self.cpu_cores_per_node
            self.cores_per_rank = 1
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'partition': self.partition,
            'cpu_cores_per_node': self.cpu_cores_per_node,
            'gpus_per_node': self.gpus_per_node,
            'gpu_vendor': self.gpu_vendor.value,
            'mpi_ranks_per_node': self.mpi_ranks_per_node,
            'cores_per_rank': self.cores_per_rank,
            'is_gpu_partition': self.is_gpu_partition,
            'detection_method': self.detection_method,
        }


@dataclass
class MPIConfiguration:
    """
    MPI configuration for a scaling run.
    
    Derived from topology - no hardcoded values.
    """
    num_nodes: int
    topology: HardwareTopology
    
    # Derived values
    total_mpi_ranks: int = field(init=False)
    mpi_ranks_per_node: int = field(init=False)
    cores_per_rank: int = field(init=False)
    total_gpus: int = field(init=False)
    
    def __post_init__(self):
        """Compute MPI configuration from topology."""
        self.mpi_ranks_per_node = self.topology.mpi_ranks_per_node
        self.cores_per_rank = self.topology.cores_per_rank
        self.total_mpi_ranks = self.num_nodes * self.mpi_ranks_per_node
        self.total_gpus = self.num_nodes * self.topology.gpus_per_node
    
    def get_mpirun_args(self) -> List[str]:
        """
        Generate mpirun arguments.
        
        Returns:
            List of mpirun arguments (not including 'mpirun' itself)
        """
        return [
            '-np', str(self.total_mpi_ranks),
            '--map-by', f'ppr:{self.mpi_ranks_per_node}:node:PE={self.cores_per_rank}',
            '--report-bindings',
        ]
    
    def get_mpirun_command_string(self) -> str:
        """Get complete mpirun command as string (without executable)."""
        args = ['mpirun'] + self.get_mpirun_args()
        return ' '.join(args)


@dataclass
class SlurmConfiguration:
    """
    SLURM job configuration.
    
    CRITICAL: --ntasks-per-node uses FULL CPU count, not MPI ranks.
    This is required for proper CPU affinity with mpirun mapping.
    """
    job_name: str
    num_nodes: int
    partition: str
    topology: HardwareTopology
    time_limit: str = "02:00:00"
    account: str = ""
    qos: str = ""
    exclusive: bool = True
    
    def get_directives(self) -> List[str]:
        """
        Generate SLURM directives.
        
        CRITICAL FIX: --ntasks-per-node = FULL CPU count, not MPI ranks
        """
        directives = [
            f"#SBATCH --job-name={self.job_name}",
            f"#SBATCH --nodes={self.num_nodes}",
            # CRITICAL: Use FULL CPU count for proper affinity
            f"#SBATCH --ntasks-per-node={self.topology.cpu_cores_per_node}",
            f"#SBATCH --time={self.time_limit}",
            f"#SBATCH --partition={self.partition}",
        ]
        
        # Add GPU directive only if GPUs present
        if self.topology.gpus_per_node > 0:
            directives.append(f"#SBATCH --gres=gpu:{self.topology.gpus_per_node}")
        
        if self.account:
            directives.append(f"#SBATCH --account={self.account}")
        
        if self.qos:
            directives.append(f"#SBATCH --qos={self.qos}")
        
        if self.exclusive:
            directives.append("#SBATCH --exclusive")
        
        return directives


@dataclass
class RunResult:
    """Result from a single scaling run."""
    
    # Identification
    run_id: str
    scaling_type: str
    node_count: int
    
    # Timing
    start_time: str = ""
    end_time: str = ""
    wall_time_seconds: float = 0.0
    
    # Resource configuration
    total_mpi_ranks: int = 0
    mpi_ranks_per_node: int = 0
    cores_per_rank: int = 0
    gpus_per_node: int = 0
    total_gpus: int = 0
    
    # Status
    status: str = "pending"  # pending, submitted, running, completed, failed
    exit_code: int = -1
    error_message: str = ""
    slurm_job_id: str = ""
    
    # Metrics
    speedup: float = 0.0
    efficiency: float = 0.0
    
    # Paths
    job_directory: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# =============================================================================
# TOPOLOGY DETECTION
# =============================================================================

class TopologyDetector:
    """
    Detect hardware topology at runtime.
    
    Detection priority:
    1. SLURM environment variables (inside job)
    2. sinfo query (on login node)
    3. System introspection (nvidia-smi, /proc/cpuinfo)
    
    NO HARDCODED VALUES - all detection is dynamic.
    """
    
    def __init__(self):
        self._cache: Dict[str, HardwareTopology] = {}
    
    def detect(self, partition: str = "") -> HardwareTopology:
        """
        Detect hardware topology for a partition.
        
        Args:
            partition: SLURM partition name (empty for current allocation)
            
        Returns:
            HardwareTopology with all values detected at runtime
        """
        cache_key = partition or "_current_"
        
        if cache_key in self._cache:
            return self._cache[cache_key]
        
        # Try detection methods in order
        topology = self._detect_from_slurm_env()
        
        if topology is None and partition:
            topology = self._detect_from_sinfo(partition)
        
        if topology is None:
            topology = self._detect_from_system()
        
        if topology is None:
            # Fallback - should not happen in production
            logger.warning("Could not detect topology, using minimal defaults")
            topology = HardwareTopology(
                partition=partition or "unknown",
                cpu_cores_per_node=os.cpu_count() or 1,
                gpus_per_node=0,
                detection_method="fallback"
            )
        
        self._cache[cache_key] = topology
        return topology
    
    def _detect_from_slurm_env(self) -> Optional[HardwareTopology]:
        """Detect from SLURM environment variables (inside job)."""
        
        if 'SLURM_JOB_ID' not in os.environ:
            return None
        
        cpus = None
        gpus = 0
        partition = os.environ.get('SLURM_JOB_PARTITION', 'unknown')
        
        # CPU detection
        if 'SLURM_CPUS_ON_NODE' in os.environ:
            cpus = int(os.environ['SLURM_CPUS_ON_NODE'])
        elif 'SLURM_JOB_CPUS_PER_NODE' in os.environ:
            val = os.environ['SLURM_JOB_CPUS_PER_NODE']
            cpus = int(val.split('(')[0])
        
        # GPU detection
        if 'SLURM_GPUS_ON_NODE' in os.environ:
            gpus = int(os.environ['SLURM_GPUS_ON_NODE'])
        elif 'SLURM_GPUS_PER_NODE' in os.environ:
            gpus = int(os.environ['SLURM_GPUS_PER_NODE'])
        elif 'CUDA_VISIBLE_DEVICES' in os.environ:
            devs = os.environ['CUDA_VISIBLE_DEVICES']
            if devs and devs.lower() not in ('', 'nodevfiles'):
                gpus = len([d for d in devs.split(',') if d.strip()])
        
        if cpus is None:
            return None
        
        gpu_vendor = GPUVendor.NVIDIA if gpus > 0 else GPUVendor.NONE
        
        logger.info(f"Detected topology from SLURM env: {cpus} CPUs, {gpus} GPUs")
        
        return HardwareTopology(
            partition=partition,
            cpu_cores_per_node=cpus,
            gpus_per_node=gpus,
            gpu_vendor=gpu_vendor,
            detection_method="slurm_env"
        )
    
    def _detect_from_sinfo(self, partition: str) -> Optional[HardwareTopology]:
        """Detect from sinfo query (on login node)."""
        
        try:
            # Query CPU count
            result = subprocess.run(
                ['sinfo', '-p', partition, '-N', '-h', '-o', '%c'],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode != 0:
                return None
            
            cpus = int(result.stdout.strip().split()[0])
            
            # Query GPU count
            result = subprocess.run(
                ['sinfo', '-p', partition, '-N', '-h', '-o', '%G'],
                capture_output=True, text=True, timeout=10
            )
            
            gpus = 0
            if result.returncode == 0 and result.stdout.strip():
                gres = result.stdout.strip().split()[0]
                match = re.search(r'gpu:(?:\w+:)?(\d+)', gres)
                if match:
                    gpus = int(match.group(1))
            
            gpu_vendor = GPUVendor.NVIDIA if gpus > 0 else GPUVendor.NONE
            
            logger.info(f"Detected topology from sinfo: {cpus} CPUs, {gpus} GPUs")
            
            return HardwareTopology(
                partition=partition,
                cpu_cores_per_node=cpus,
                gpus_per_node=gpus,
                gpu_vendor=gpu_vendor,
                detection_method="sinfo"
            )
            
        except Exception as e:
            logger.debug(f"sinfo detection failed: {e}")
            return None
    
    def _detect_from_system(self) -> Optional[HardwareTopology]:
        """Detect from system introspection."""
        
        cpus = os.cpu_count() or 1
        gpus = 0
        gpu_vendor = GPUVendor.NONE
        
        # Try nvidia-smi
        try:
            result = subprocess.run(
                ['nvidia-smi', '--query-gpu=count', '--format=csv,noheader'],
                capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                gpus = int(result.stdout.strip().split('\n')[0])
                gpu_vendor = GPUVendor.NVIDIA
        except Exception:
            pass
        
        logger.info(f"Detected topology from system: {cpus} CPUs, {gpus} GPUs")
        
        return HardwareTopology(
            partition="local",
            cpu_cores_per_node=cpus,
            gpus_per_node=gpus,
            gpu_vendor=gpu_vendor,
            detection_method="system"
        )


# Singleton detector
_detector = None

def get_detector() -> TopologyDetector:
    """Get the singleton topology detector."""
    global _detector
    if _detector is None:
        _detector = TopologyDetector()
    return _detector


def detect_topology(partition: str = "") -> HardwareTopology:
    """Convenience function to detect topology."""
    return get_detector().detect(partition)


# =============================================================================
# GPU BINDING SCRIPT GENERATION
# =============================================================================

def generate_gpu_binding_script(output_dir: Path) -> Path:
    """
    Generate the GPU binding script.
    
    The script uses OMPI_COMM_WORLD_LOCAL_RANK to set CUDA_VISIBLE_DEVICES,
    ensuring each MPI rank gets a unique GPU.
    
    Args:
        output_dir: Directory to write bind.sh
        
    Returns:
        Path to generated bind.sh
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    bind_path = output_dir / "bind.sh"
    with open(bind_path, 'w') as f:
        f.write(GPU_BIND_SCRIPT)
    
    os.chmod(bind_path, 0o755)
    
    logger.debug(f"Generated GPU binding script: {bind_path}")
    return bind_path


def get_gpu_binding_script_content() -> str:
    """Get the GPU binding script content."""
    return GPU_BIND_SCRIPT


# =============================================================================
# JOB SCRIPT GENERATION
# =============================================================================

def generate_job_script(
    slurm_config: SlurmConfiguration,
    mpi_config: MPIConfiguration,
    binary_dir: str,
    executable: str,
    args: List[str] = None,
    modules: List[str] = None,
    working_dir: str = ".",
) -> str:
    """
    Generate a complete SLURM job script.
    
    CRITICAL FIXES:
    1. BINARY points to absolute build directory (not ${PWD})
    2. Executable is the actual binary (not bind.sh)
    3. bind.sh is generated inline and wraps the executable
    4. mpirun uses ppr:R:node:PE=C mapping
    5. SLURM uses full CPU count for --ntasks-per-node
    
    Args:
        slurm_config: SLURM configuration
        mpi_config: MPI configuration
        binary_dir: Absolute path to build directory
        executable: Name of the executable
        args: Arguments for executable
        modules: Module load commands
        working_dir: Working directory for job
        
    Returns:
        Complete job script as string
    """
    args = args or []
    modules = modules or []
    topology = slurm_config.topology
    
    # Build script
    lines = [
        "#!/bin/bash",
        "# " + "=" * 75,
        "# SLURM Job Script - Generated by HPC-ScaleTest",
        "# " + "=" * 75,
        f"# Partition: {slurm_config.partition}",
        f"# Nodes: {slurm_config.num_nodes}",
        f"# CPUs per node: {topology.cpu_cores_per_node}",
        f"# GPUs per node: {topology.gpus_per_node}",
        f"#",
        f"# MPI Configuration:",
        f"#   Total ranks: {mpi_config.total_mpi_ranks}",
        f"#   Ranks per node: {mpi_config.mpi_ranks_per_node}",
        f"#   Cores per rank: {mpi_config.cores_per_rank}",
        "# " + "=" * 75,
        "",
    ]
    
    # SLURM directives
    lines.extend(slurm_config.get_directives())
    lines.append(f"#SBATCH --output={working_dir}/job_%j.out")
    lines.append(f"#SBATCH --error={working_dir}/job_%j.err")
    lines.append("")
    
    # Environment setup
    lines.append("# " + "-" * 75)
    lines.append("# Environment Setup")
    lines.append("# " + "-" * 75)
    for mod in modules:
        lines.append(mod)
    lines.append("")
    
    # Binary location - CRITICAL: use absolute path
    lines.append("# CRITICAL: BINARY must be absolute path to build directory")
    lines.append(f"export BINARY={binary_dir}")
    lines.append("")
    
    # Job info
    lines.append("echo \"" + "=" * 60 + "\"")
    lines.append('echo "Job ID: $SLURM_JOB_ID"')
    lines.append('echo "Nodes: $SLURM_NNODES"')
    lines.append(f'echo "CPUs per node: {topology.cpu_cores_per_node}"')
    lines.append(f'echo "GPUs per node: {topology.gpus_per_node}"')
    lines.append(f'echo "MPI ranks per node: {mpi_config.mpi_ranks_per_node}"')
    lines.append(f'echo "Cores per rank: {mpi_config.cores_per_rank}"')
    lines.append('echo "BINARY: $BINARY"')
    lines.append("echo \"" + "=" * 60 + "\"")
    lines.append("")
    
    lines.append(f"cd {working_dir}")
    lines.append(f"export OMP_NUM_THREADS={mpi_config.cores_per_rank}")
    lines.append("")
    
    # GPU binding script - only for GPU jobs
    if topology.gpus_per_node > 0:
        lines.append("# " + "-" * 75)
        lines.append("# GPU Binding Script")
        lines.append("# Uses OMPI_COMM_WORLD_LOCAL_RANK to bind each rank to a unique GPU")
        lines.append("# " + "-" * 75)
        lines.append("cat > bind.sh << 'BIND_EOF'")
        lines.append(GPU_BIND_SCRIPT.strip())
        lines.append("BIND_EOF")
        lines.append("chmod +x bind.sh")
        lines.append("")
    
    # Build mpirun command
    mpi_cmd_parts = ['mpirun'] + mpi_config.get_mpirun_args()
    
    # Add GPU binding wrapper if needed
    if topology.gpus_per_node > 0:
        mpi_cmd_parts.append('./bind.sh')
    
    # Add executable
    mpi_cmd_parts.append(f'$BINARY/{executable}')
    
    # Add arguments
    mpi_cmd_parts.extend(args)
    
    mpi_cmd = ' '.join(mpi_cmd_parts)
    
    # Execute with timing
    lines.append("# " + "-" * 75)
    lines.append("# Execute Application")
    lines.append("# " + "-" * 75)
    lines.append('echo ""')
    lines.append('echo "Starting: $(date)"')
    lines.append(f'echo "Command: {mpi_cmd}"')
    lines.append('echo ""')
    lines.append("")
    lines.append('start_time=$(date +%s.%N)')
    lines.append("")
    lines.append(mpi_cmd)
    lines.append("")
    lines.append('exit_code=$?')
    lines.append('end_time=$(date +%s.%N)')
    lines.append('elapsed=$(echo "$end_time - $start_time" | bc)')
    lines.append("")
    lines.append("echo \"" + "=" * 60 + "\"")
    lines.append('echo "Completed: $(date)"')
    lines.append('echo "Exit code: $exit_code"')
    lines.append('echo "Elapsed: $elapsed seconds"')
    lines.append("echo \"" + "=" * 60 + "\"")
    lines.append("")
    
    # Write timing JSON
    lines.append("# Write timing JSON for result parsing")
    lines.append('cat > timing.json << EOF')
    lines.append('{')
    lines.append('  "wall_time": $elapsed,')
    lines.append('  "exit_code": $exit_code,')
    lines.append('  "start_time": "$start_time",')
    lines.append('  "end_time": "$end_time"')
    lines.append('}')
    lines.append('EOF')
    lines.append("")
    lines.append('exit $exit_code')
    
    return '\n'.join(lines)


# =============================================================================
# NODE SEQUENCE GENERATION
# =============================================================================

def generate_node_sequence(max_nodes: int, min_nodes: int = 1) -> List[int]:
    """
    Generate node sequence using powers of 2.
    
    FIXES: Removes hardcoded sequences like [1, 2, 4].
    Dynamically generates based on max_nodes.
    
    Args:
        max_nodes: Maximum number of nodes
        min_nodes: Minimum number of nodes (default 1)
        
    Returns:
        List of node counts (powers of 2 up to max_nodes)
    """
    sequence = []
    n = min_nodes
    
    # Generate powers of 2
    while n <= max_nodes:
        sequence.append(n)
        n *= 2
    
    # Include max_nodes if not a power of 2
    if sequence[-1] != max_nodes:
        sequence.append(max_nodes)
    
    return sequence


# =============================================================================
# RESULT TRACKING
# =============================================================================

class IncrementalResultWriter:
    """
    Write scaling results incrementally.
    
    Results are written immediately after each run, not batched at the end.
    This allows real-time analysis and prevents data loss.
    
    Output structure:
        run_data/
        ├── weak_scaling_report_node1.json
        ├── weak_scaling_report_node2.json
        ├── weak_scaling_report_node4.json
        ├── summary.json
        ├── scaling_report.json
        └── scaling_report.csv
    """
    
    def __init__(
        self,
        output_dir: Path,
        scaling_type: str,
        partition: str = "",
        test_name: str = "scaling_test"
    ):
        self.output_dir = Path(output_dir)
        self.scaling_type = scaling_type.lower()
        self.partition = partition
        self.test_name = test_name
        
        # Create run_data directory
        self.data_dir = self.output_dir / "run_data"
        self.data_dir.mkdir(parents=True, exist_ok=True)
        
        # Track results
        self._results: Dict[int, RunResult] = {}
        self._baseline_time: Optional[float] = None
        self._start_time = datetime.now().isoformat()
        
        logger.info(f"Initialized result writer: {self.data_dir}")
    
    def write_run_result(self, result: RunResult) -> Path:
        """
        Write a single run's result IMMEDIATELY.
        
        Args:
            result: RunResult from completed run
            
        Returns:
            Path to the written JSON file
        """
        # Compute metrics
        self._compute_metrics(result)
        
        # Generate filename
        filename = f"{self.scaling_type}_scaling_report_node{result.node_count}.json"
        filepath = self.data_dir / filename
        
        # Write JSON
        data = result.to_dict()
        data['timestamp'] = datetime.now().isoformat()
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)
        
        logger.info(f"✓ Wrote result: {filepath}")
        
        # Store for summary
        self._results[result.node_count] = result
        
        # Update baseline
        if result.node_count == 1 and result.status == "completed":
            self._baseline_time = result.wall_time_seconds
        
        return filepath
    
    def create_pending_result(
        self,
        node_count: int,
        mpi_config: MPIConfiguration,
        topology: HardwareTopology,
        job_directory: str = "",
        slurm_job_id: str = ""
    ) -> RunResult:
        """Create and write a pending result before the run starts."""
        result = RunResult(
            run_id=f"{self.scaling_type}_node{node_count}",
            scaling_type=self.scaling_type,
            node_count=node_count,
            start_time=datetime.now().isoformat(),
            total_mpi_ranks=mpi_config.total_mpi_ranks,
            mpi_ranks_per_node=mpi_config.mpi_ranks_per_node,
            cores_per_rank=mpi_config.cores_per_rank,
            gpus_per_node=topology.gpus_per_node,
            total_gpus=mpi_config.total_gpus,
            status="pending",
            job_directory=job_directory,
            slurm_job_id=slurm_job_id,
        )
        
        self.write_run_result(result)
        return result
    
    def update_run_status(
        self,
        node_count: int,
        status: str,
        wall_time: float = 0.0,
        exit_code: int = 0,
        error_message: str = ""
    ) -> None:
        """Update status of an existing run."""
        if node_count not in self._results:
            logger.warning(f"No result for node count {node_count}")
            return
        
        result = self._results[node_count]
        result.status = status
        result.wall_time_seconds = wall_time
        result.exit_code = exit_code
        result.error_message = error_message
        
        if status == "completed":
            result.end_time = datetime.now().isoformat()
        
        self.write_run_result(result)
    
    def _compute_metrics(self, result: RunResult) -> None:
        """Compute speedup and efficiency."""
        if self._baseline_time is None or self._baseline_time <= 0:
            return
        
        if result.wall_time_seconds <= 0:
            return
        
        if self.scaling_type == "strong":
            result.speedup = self._baseline_time / result.wall_time_seconds
            result.efficiency = result.speedup / result.node_count * 100
        else:
            result.efficiency = (self._baseline_time / result.wall_time_seconds) * 100
            result.speedup = result.node_count
    
    def write_summary(self) -> Path:
        """Write summary.json after all runs."""
        sorted_results = sorted(self._results.values(), key=lambda r: r.node_count)
        
        summary = {
            'test_name': self.test_name,
            'scaling_type': self.scaling_type,
            'partition': self.partition,
            'start_time': self._start_time,
            'end_time': datetime.now().isoformat(),
            'total_runs': len(self._results),
            'completed_runs': sum(1 for r in self._results.values() if r.status == "completed"),
            'failed_runs': sum(1 for r in self._results.values() if r.status == "failed"),
            'node_sequence': sorted(self._results.keys()),
            'baseline_time': self._baseline_time or 0,
            'results': [r.to_dict() for r in sorted_results],
        }
        
        filepath = self.data_dir / "summary.json"
        with open(filepath, 'w') as f:
            json.dump(summary, f, indent=2)
        
        logger.info(f"✓ Wrote summary: {filepath}")
        return filepath
    
    def write_csv_report(self) -> Path:
        """Write CSV report for easy post-processing."""
        sorted_results = sorted(self._results.values(), key=lambda r: r.node_count)
        
        lines = [
            "nodes,gpus_per_node,total_gpus,mpi_ranks,wall_time_s,speedup,efficiency_pct,status,timestamp"
        ]
        
        for r in sorted_results:
            lines.append(
                f"{r.node_count},{r.gpus_per_node},{r.total_gpus},"
                f"{r.total_mpi_ranks},{r.wall_time_seconds:.2f},"
                f"{r.speedup:.2f},{r.efficiency:.1f},{r.status},{r.end_time}"
            )
        
        filepath = self.data_dir / "scaling_report.csv"
        with open(filepath, 'w') as f:
            f.write('\n'.join(lines))
        
        logger.info(f"✓ Wrote CSV: {filepath}")
        return filepath
    
    def write_aggregated_report(self) -> Path:
        """Write aggregated JSON report."""
        sorted_results = sorted(self._results.values(), key=lambda r: r.node_count)
        
        report = {
            'test_name': self.test_name,
            'scaling_type': self.scaling_type,
            'partition': self.partition,
            'generated_at': datetime.now().isoformat(),
            'baseline': {
                'nodes': 1,
                'time_seconds': self._baseline_time or 0
            },
            'results': [
                {
                    'nodes': r.node_count,
                    'gpus_per_node': r.gpus_per_node,
                    'total_gpus': r.total_gpus,
                    'total_ranks': r.total_mpi_ranks,
                    'time_seconds': r.wall_time_seconds,
                    'speedup': r.speedup,
                    'efficiency': r.efficiency,
                    'status': r.status,
                }
                for r in sorted_results
            ]
        }
        
        filepath = self.data_dir / "scaling_report.json"
        with open(filepath, 'w') as f:
            json.dump(report, f, indent=2)
        
        logger.info(f"✓ Wrote aggregated report: {filepath}")
        return filepath
    
    def get_result(self, node_count: int) -> Optional[RunResult]:
        """Get result for a specific node count."""
        return self._results.get(node_count)


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def create_mpi_config(
    num_nodes: int,
    partition: str = "",
    topology: HardwareTopology = None
) -> MPIConfiguration:
    """
    Create MPI configuration with automatic topology detection.
    
    Args:
        num_nodes: Number of nodes
        partition: SLURM partition (for topology detection)
        topology: Pre-detected topology (optional)
        
    Returns:
        MPIConfiguration with all values derived from topology
    """
    if topology is None:
        topology = detect_topology(partition)
    
    return MPIConfiguration(num_nodes=num_nodes, topology=topology)


def create_slurm_config(
    job_name: str,
    num_nodes: int,
    partition: str,
    topology: HardwareTopology = None,
    time_limit: str = "02:00:00",
    account: str = "",
    qos: str = "",
) -> SlurmConfiguration:
    """Create SLURM configuration with automatic topology detection."""
    if topology is None:
        topology = detect_topology(partition)
    
    return SlurmConfiguration(
        job_name=job_name,
        num_nodes=num_nodes,
        partition=partition,
        topology=topology,
        time_limit=time_limit,
        account=account,
        qos=qos,
    )


# =============================================================================
# SELF-TEST
# =============================================================================

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
    
    print("=" * 70)
    print(" Unified Execution Module - Self Test")
    print("=" * 70)
    
    # Test 1: Topology detection and derivation
    print("\n[1] Testing topology derivation...")
    
    test_configs = [
        (32, 4, 4, 8),    # Leonardo
        (128, 8, 8, 16),  # LUMI-G
        (64, 0, 64, 1),   # CPU-only
    ]
    
    for cpus, gpus, expected_ranks, expected_cores in test_configs:
        topo = HardwareTopology(
            partition="test",
            cpu_cores_per_node=cpus,
            gpus_per_node=gpus,
            detection_method="test"
        )
        assert topo.mpi_ranks_per_node == expected_ranks
        assert topo.cores_per_rank == expected_cores
        print(f"  ✓ {cpus} CPUs, {gpus} GPUs → {topo.mpi_ranks_per_node} ranks, {topo.cores_per_rank} cores/rank")
    
    # Test 2: MPI command generation
    print("\n[2] Testing MPI command generation...")
    
    topo = HardwareTopology(
        partition="boost_usr_prod",
        cpu_cores_per_node=32,
        gpus_per_node=4,
        detection_method="test"
    )
    
    for nodes in [1, 2, 4, 8]:
        config = MPIConfiguration(num_nodes=nodes, topology=topo)
        cmd = config.get_mpirun_command_string()
        expected_np = nodes * 4
        assert f"-np {expected_np}" in cmd
        assert "ppr:4:node:PE=8" in cmd
        print(f"  ✓ {nodes} nodes: {cmd}")
    
    # Test 3: SLURM directives
    print("\n[3] Testing SLURM directives...")
    
    slurm = SlurmConfiguration(
        job_name="test",
        num_nodes=4,
        partition="boost_usr_prod",
        topology=topo
    )
    directives = '\n'.join(slurm.get_directives())
    assert "--ntasks-per-node=32" in directives  # Full CPU count
    assert "--gres=gpu:4" in directives
    print("  ✓ --ntasks-per-node=32 (full CPU count)")
    print("  ✓ --gres=gpu:4")
    
    # Test 4: Job script generation
    print("\n[4] Testing job script generation...")
    
    mpi = MPIConfiguration(num_nodes=4, topology=topo)
    script = generate_job_script(
        slurm_config=slurm,
        mpi_config=mpi,
        binary_dir="/path/to/build",
        executable="iPIC3D",
        args=["os-stdin"],
        modules=["module load cuda/12.0"]
    )
    
    assert "export BINARY=/path/to/build" in script
    assert "mpirun -np 16" in script
    assert "ppr:4:node:PE=8" in script
    assert "./bind.sh $BINARY/iPIC3D" in script
    assert "CUDA_VISIBLE_DEVICES" in script
    print("  ✓ BINARY set to absolute path")
    print("  ✓ mpirun with correct mapping")
    print("  ✓ bind.sh wraps executable")
    
    # Test 5: Node sequence generation
    print("\n[5] Testing node sequence generation...")
    
    seq = generate_node_sequence(max_nodes=8)
    assert seq == [1, 2, 4, 8], f"Expected [1, 2, 4, 8], got {seq}"
    print(f"  ✓ max_nodes=8: {seq}")
    
    seq = generate_node_sequence(max_nodes=6)
    assert seq == [1, 2, 4, 6], f"Expected [1, 2, 4, 6], got {seq}"
    print(f"  ✓ max_nodes=6: {seq}")
    
    seq = generate_node_sequence(max_nodes=16)
    assert seq == [1, 2, 4, 8, 16], f"Expected [1, 2, 4, 8, 16], got {seq}"
    print(f"  ✓ max_nodes=16: {seq}")
    
    # Test 6: Result writer
    print("\n[6] Testing result writer...")
    
    import tempfile
    with tempfile.TemporaryDirectory() as tmpdir:
        writer = IncrementalResultWriter(
            output_dir=Path(tmpdir),
            scaling_type="weak",
            partition="boost_usr_prod",
            test_name="test"
        )
        
        for nodes in [1, 2, 4]:
            config = MPIConfiguration(num_nodes=nodes, topology=topo)
            result = writer.create_pending_result(
                node_count=nodes,
                mpi_config=config,
                topology=topo,
                job_directory=f"{tmpdir}/node{nodes}"
            )
            
            writer.update_run_status(
                node_count=nodes,
                status="completed",
                wall_time=100.0 + nodes * 5,
                exit_code=0
            )
        
        writer.write_summary()
        writer.write_csv_report()
        writer.write_aggregated_report()
        
        data_dir = Path(tmpdir) / "run_data"
        assert (data_dir / "summary.json").exists()
        assert (data_dir / "scaling_report.csv").exists()
        assert (data_dir / "scaling_report.json").exists()
        print("  ✓ summary.json created")
        print("  ✓ scaling_report.csv created")
        print("  ✓ scaling_report.json created")
    
    print("\n" + "=" * 70)
    print(" ALL TESTS PASSED")
    print("=" * 70)
