#!/usr/bin/env python3
"""
GPU Binding Script Generator

Generates wrapper scripts for proper GPU binding in MPI applications.
Compatible with OpenMPI and Intel MPI.
"""

import os
import stat


def generate_gpu_bind_script(output_dir=".", script_name="bind_gpu", gpu_vendor="nvidia"):
    """
    Generate GPU binding wrapper script.
    
    This script:
    1. Detects local rank (rank within node)
    2. Sets GPU device visibility (CUDA_VISIBLE_DEVICES or ROCR_VISIBLE_DEVICES)
    3. Logs the binding
    4. Executes the actual application
    
    Args:
        output_dir: Directory to write script
        script_name: Name of the binding script
        gpu_vendor: 'nvidia' or 'amd'
    
    Returns:
        Path to generated script
    """
    
    script_path = os.path.join(output_dir, script_name)
    
    # Determine device variable based on vendor
    if gpu_vendor.lower() == 'nvidia':
        device_var = 'CUDA_VISIBLE_DEVICES'
    elif gpu_vendor.lower() == 'amd':
        device_var = 'ROCR_VISIBLE_DEVICES'
    else:
        device_var = 'GPU_DEVICE_ORDINAL'
    
    script_content = '''#!/bin/bash
#
# GPU Binding Wrapper Script
# Auto-generated by HPC-ScaleTest
#
# Purpose: Bind each MPI rank to a specific GPU
# Usage: mpirun -np N [options] bind_gpu ./application [args]
#

# Detect local rank (rank within this node)
# Try multiple methods for different MPI implementations

if [ -n "$OMPI_COMM_WORLD_LOCAL_RANK" ]; then
    # OpenMPI
    export LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
elif [ -n "$MPI_LOCALRANKID" ]; then
    # Intel MPI
    export LOCAL_RANK=$MPI_LOCALRANKID
elif [ -n "$SLURM_LOCALID" ]; then
    # SLURM
    export LOCAL_RANK=$SLURM_LOCALID
elif [ -n "$PMI_RANK" ]; then
    # Some MPICH implementations
    # This is global rank, need to compute local rank
    # Fallback: try to use modulo number of GPUs
    NGPUS=4  # Default, update if needed
    export LOCAL_RANK=$((PMI_RANK % NGPUS))
else
    # Fallback: assume rank 0
    echo "[WARNING] Could not determine local rank, using 0"
    export LOCAL_RANK=0
fi

# Set GPU device visibility
export {device_var}=$LOCAL_RANK

# Log the binding (helpful for debugging)
echo "[LOG] Rank ${{OMPI_COMM_WORLD_RANK:-$PMI_RANK:-unknown}} (local rank $LOCAL_RANK): bind to GPU $LOCAL_RANK"
echo ""

# Execute the actual application with all arguments
exec "$@"
'''.format(device_var=device_var)
    
    # Write script
    with open(script_path, 'w') as f:
        f.write(script_content)
    
    # Make executable
    st = os.stat(script_path)
    os.chmod(script_path, st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    
    return script_path


def generate_intel_mpi_bind_script(output_dir=".", script_name="bind_gpu_intel"):
    """
    Generate Intel MPI specific binding script.
    
    Intel MPI uses different environment variables.
    """
    
    script_path = os.path.join(output_dir, script_name)
    
    script_content = '''#!/bin/bash
#
# GPU Binding Wrapper Script (Intel MPI optimized)
# Auto-generated by HPC-ScaleTest
#

# Intel MPI specific local rank
if [ -n "$MPI_LOCALRANKID" ]; then
    export LOCAL_RANK=$MPI_LOCALRANKID
elif [ -n "$SLURM_LOCALID" ]; then
    export LOCAL_RANK=$SLURM_LOCALID
else
    export LOCAL_RANK=0
fi

# Set GPU device
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK

# For Intel MPI, can also use I_MPI environment variables
export I_MPI_PIN_DOMAIN=auto
export I_MPI_PIN_ORDER=scatter

# Log binding
echo "[LOG] Intel MPI: local rank $LOCAL_RANK → GPU $LOCAL_RANK"

# Execute application
exec "$@"
'''
    
    with open(script_path, 'w') as f:
        f.write(script_content)
    
    st = os.stat(script_path)
    os.chmod(script_path, st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    
    return script_path


def test_binding_scripts():
    """Test script generation."""
    print("Generating GPU binding scripts...")
    print()
    
    # Generate OpenMPI NVIDIA script
    script1 = generate_gpu_bind_script(".", "bind_gpu", "nvidia")
    print("✓ Generated: {} (OpenMPI + NVIDIA)".format(script1))
    
    # Generate AMD script
    script2 = generate_gpu_bind_script(".", "bind_gpu_amd", "amd")
    print("✓ Generated: {} (OpenMPI + AMD)".format(script2))
    
    # Generate Intel MPI script
    script3 = generate_intel_mpi_bind_script(".", "bind_gpu_intel")
    print("✓ Generated: {} (Intel MPI)".format(script3))
    
    print()
    print("Example usage:")
    print("  OpenMPI:   mpirun -np 4 --map-by ppr:4:node --bind-to core --cpus-per-proc 8 {} ./app args".format(script1))
    print("  Intel MPI: mpirun -np 4 {} ./app args".format(script3))
    print()
    print("Scripts are executable and ready to use!")


if __name__ == '__main__':
    test_binding_scripts()
